[package]
name = "merkle_partial"
version = "0.0.0"
authors = ["Matt Garnett <matt.garnett@consensys.net>"]
edition = "2018"

[dependencies]
hashing = { path = "../hashing" }
tree_hash = { path = "../tree_hash" }
ethereum-types = "0.6.0"
ssz_types = { path = "../ssz_types" }
typenum = "1.10.0"
eth2_ssz_derive = "0.1.0"
eth2_ssz = "0.1.0"
