[package]
name = "merkle_partial"
version = "0.0.0"
authors = ["Matt Garnett <matt.garnett@consensys.net>"]
edition = "2018"

[dependencies]
ethereum-types = "0.6.0"
typenum = "1.10.0"
hashing = { path = "../hashing" }
tree_hash = { path = "../tree_hash" }
ssz_types = { path = "../ssz_types" }
eth2_ssz = { path = "../ssz" }
eth2_ssz_derive = { path = "../ssz_derive" }
